#!/bin/sh

## Display config per device
# Check if HDMI is used, if so then disable laptop display and use HDMI at 1080p.
xrandr | grep "HDMI-1 connected" && xrandr --output HDMI-1 --primary --mode 1920x1080 --rate 60 && xrandr --output eDP-1 --off
xrandr | grep "DP-1 connected" && xrandr --output DP-1 --mode 3840x2160 --scale 0.5

## Keyboard and input settings / config
# Set keyboard layout to English-GB/UK
setxkbmap -layout gb

# Start dbus daemon
dbus-daemon --session --address="unix:path=$XDG_RUNTIME_DIR/bus" &

# Load xrdb with values.
xrdb -merge $XDG_CONFIG_HOME/x11/Xdefaults

# Set keboard delay / rate:
xset r rate 240 40

## Launch daemons, rendering tools and applets.
# Keys, tools and settings applets.
# sxhkd &
nm-applet &
blueman-applet &
mullvad-vpn &

# Pipewire Audio, wireplumber and pulse session started via pipewire configuration exec.
pipewire &

# Monero node
monerod --detach --prune-blockchain --check-updates disabled --non-interactive --max-concurrency 2 &

# Emacs server
/usr/bin/emacs --daemon &

# Desktop related
picom &
unclutter &
setbg.sh -w &
dunst &
flameshot &

# Music
[ ! $(pgrep mpd) ] && mpd

# Keys
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
dbus-update-activation-environment -all

# Daemonise pcmanfm with dbus enabled featureset.
#dbus-launch pcmanfm -d &

# Run window manager.
exec i3

