import = [ "~/.config/alacritty/catppuccin-macchiato.toml" ]

[font]
size = 12

[font.normal]
#family = "hack"
family = "Hack Nerd Font Mono"

[window]
decorations = "none"

[window.padding]
x = 0
y = 0

[keyboard]
bindings = [
{ key = "C", mods = "Control|Shift", action = "None" },
{ key = "C", mods = "Alt|Shift", action = "Copy" },
{ key = "V", mods = "Control|Shift", action = "None" },
{ key = "V", mods = "Alt|Shift", action = "Paste" },
]
