import = [ "~/.config/alacritty/catppuccin-macchiato.toml" ]

[font]
size = 12

[font.normal]
#family = "hack"
family = "Hack Nerd Font Mono"

[window]
decorations = "none"

[window.padding]
x = 0
y = 0
